// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/area.proto

package area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Area service

func NewAreaEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Area service

type AreaService interface {
	CreateArea(ctx context.Context, in *Request_AreaInfo, opts ...client.CallOption) (*ResponseMessage, error)
	DelArea(ctx context.Context, in *Request_AreaID, opts ...client.CallOption) (*ResponseMessage, error)
	FindAll(ctx context.Context, in *Request_NULL, opts ...client.CallOption) (*Response_AreaInfos, error)
}

type areaService struct {
	c    client.Client
	name string
}

func NewAreaService(name string, c client.Client) AreaService {
	return &areaService{
		c:    c,
		name: name,
	}
}

func (c *areaService) CreateArea(ctx context.Context, in *Request_AreaInfo, opts ...client.CallOption) (*ResponseMessage, error) {
	req := c.c.NewRequest(c.name, "Area.CreateArea", in)
	out := new(ResponseMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaService) DelArea(ctx context.Context, in *Request_AreaID, opts ...client.CallOption) (*ResponseMessage, error) {
	req := c.c.NewRequest(c.name, "Area.DelArea", in)
	out := new(ResponseMessage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *areaService) FindAll(ctx context.Context, in *Request_NULL, opts ...client.CallOption) (*Response_AreaInfos, error) {
	req := c.c.NewRequest(c.name, "Area.FindAll", in)
	out := new(Response_AreaInfos)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Area service

type AreaHandler interface {
	CreateArea(context.Context, *Request_AreaInfo, *ResponseMessage) error
	DelArea(context.Context, *Request_AreaID, *ResponseMessage) error
	FindAll(context.Context, *Request_NULL, *Response_AreaInfos) error
}

func RegisterAreaHandler(s server.Server, hdlr AreaHandler, opts ...server.HandlerOption) error {
	type area interface {
		CreateArea(ctx context.Context, in *Request_AreaInfo, out *ResponseMessage) error
		DelArea(ctx context.Context, in *Request_AreaID, out *ResponseMessage) error
		FindAll(ctx context.Context, in *Request_NULL, out *Response_AreaInfos) error
	}
	type Area struct {
		area
	}
	h := &areaHandler{hdlr}
	return s.Handle(s.NewHandler(&Area{h}, opts...))
}

type areaHandler struct {
	AreaHandler
}

func (h *areaHandler) CreateArea(ctx context.Context, in *Request_AreaInfo, out *ResponseMessage) error {
	return h.AreaHandler.CreateArea(ctx, in, out)
}

func (h *areaHandler) DelArea(ctx context.Context, in *Request_AreaID, out *ResponseMessage) error {
	return h.AreaHandler.DelArea(ctx, in, out)
}

func (h *areaHandler) FindAll(ctx context.Context, in *Request_NULL, out *Response_AreaInfos) error {
	return h.AreaHandler.FindAll(ctx, in, out)
}
