// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.9.0
// source: proto/area.proto

package area

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request_NULL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request_NULL) Reset() {
	*x = Request_NULL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_area_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_NULL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_NULL) ProtoMessage() {}

func (x *Request_NULL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_NULL.ProtoReflect.Descriptor instead.
func (*Request_NULL) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{0}
}

type Request_AreaID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *Request_AreaID) Reset() {
	*x = Request_AreaID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_area_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_AreaID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_AreaID) ProtoMessage() {}

func (x *Request_AreaID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_AreaID.ProtoReflect.Descriptor instead.
func (*Request_AreaID) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{1}
}

func (x *Request_AreaID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Request_AreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description"`
}

func (x *Request_AreaInfo) Reset() {
	*x = Request_AreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_area_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_AreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_AreaInfo) ProtoMessage() {}

func (x *Request_AreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_AreaInfo.ProtoReflect.Descriptor instead.
func (*Request_AreaInfo) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{2}
}

func (x *Request_AreaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request_AreaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Response_AreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
}

func (x *Response_AreaInfo) Reset() {
	*x = Response_AreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_area_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_AreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_AreaInfo) ProtoMessage() {}

func (x *Response_AreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_AreaInfo.ProtoReflect.Descriptor instead.
func (*Response_AreaInfo) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{3}
}

func (x *Response_AreaInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response_AreaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Response_AreaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Response_AreaInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*Response_AreaInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos"`
}

func (x *Response_AreaInfos) Reset() {
	*x = Response_AreaInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_area_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_AreaInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_AreaInfos) ProtoMessage() {}

func (x *Response_AreaInfos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_AreaInfos.ProtoReflect.Descriptor instead.
func (*Response_AreaInfos) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{4}
}

func (x *Response_AreaInfos) GetInfos() []*Response_AreaInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_area_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_area_proto protoreflect.FileDescriptor

var file_proto_area_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x61, 0x72, 0x65, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x10, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x43, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x41, 0x72, 0x65, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xb6, 0x01, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x3c, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x12, 0x16, 0x2e, 0x61, 0x72, 0x65, 0x61,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x16, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x44, 0x65, 0x6c,
	0x41, 0x72, 0x65, 0x61, 0x12, 0x14, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x61, 0x72, 0x65,
	0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x12, 0x2e,
	0x61, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x4e, 0x55, 0x4c,
	0x4c, 0x1a, 0x18, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x61, 0x72, 0x65, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_area_proto_rawDescOnce sync.Once
	file_proto_area_proto_rawDescData = file_proto_area_proto_rawDesc
)

func file_proto_area_proto_rawDescGZIP() []byte {
	file_proto_area_proto_rawDescOnce.Do(func() {
		file_proto_area_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_area_proto_rawDescData)
	})
	return file_proto_area_proto_rawDescData
}

var file_proto_area_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_area_proto_goTypes = []interface{}{
	(*Request_NULL)(nil),       // 0: area.Request_NULL
	(*Request_AreaID)(nil),     // 1: area.Request_AreaID
	(*Request_AreaInfo)(nil),   // 2: area.Request_AreaInfo
	(*Response_AreaInfo)(nil),  // 3: area.Response_AreaInfo
	(*Response_AreaInfos)(nil), // 4: area.Response_AreaInfos
	(*ResponseMessage)(nil),    // 5: area.Response_message
}
var file_proto_area_proto_depIdxs = []int32{
	3, // 0: area.Response_AreaInfos.infos:type_name -> area.Response_AreaInfo
	2, // 1: area.Area.CreateArea:input_type -> area.Request_AreaInfo
	1, // 2: area.Area.DelArea:input_type -> area.Request_AreaID
	0, // 3: area.Area.FindAll:input_type -> area.Request_NULL
	5, // 4: area.Area.CreateArea:output_type -> area.Response_message
	5, // 5: area.Area.DelArea:output_type -> area.Response_message
	4, // 6: area.Area.FindAll:output_type -> area.Response_AreaInfos
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_area_proto_init() }
func file_proto_area_proto_init() {
	if File_proto_area_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_area_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_NULL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_area_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_AreaID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_area_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_AreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_area_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_AreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_area_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_AreaInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_area_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_area_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_area_proto_goTypes,
		DependencyIndexes: file_proto_area_proto_depIdxs,
		MessageInfos:      file_proto_area_proto_msgTypes,
	}.Build()
	File_proto_area_proto = out.File
	file_proto_area_proto_rawDesc = nil
	file_proto_area_proto_goTypes = nil
	file_proto_area_proto_depIdxs = nil
}
